#!/usr/bin/env python3
"""Build the bundled dictionary and the list of solvable starting words.

Inputs are two public word lists (see SOURCES). The output, src/words.js, holds
every legal 2-5 letter word plus a pre-verified list of 5-letter openers that
have at least one full solution path down to a 2-letter word.

Usage: python3 tools/build_words.py <twl.txt> <popular.txt>
"""
import sys
from string import ascii_lowercase

SOURCES = {
    "twl": "github.com/redbo/scrabble (TWL06 tournament word list)",
    "popular": "github.com/dolph/dictionary (popular.txt)",
}
MIN_LEN, MAX_LEN = 2, 5


def load(path):
    with open(path) as fh:
        return {w for w in (line.strip().lower() for line in fh) if w.isalpha()}


def by_length(words):
    out = {n: set() for n in range(MIN_LEN, MAX_LEN + 1)}
    for w in words:
        if MIN_LEN <= len(w) <= MAX_LEN:
            out[len(w)].add(w)
    return out


def next_words(word, dictionary):
    """Every word reachable in one round: keep len-2 consecutive letters, add one."""
    n = len(word)
    if n == 2:
        return {c for c in "ai" if c in word}
    keep = n - 2
    found = set()
    for i in range(n - keep + 1):
        block = word[i:i + keep]
        for c in ascii_lowercase:
            for candidate in (c + block, block + c):
                if candidate in dictionary[n - 1]:
                    found.add(candidate)
    return found


def depth(word, dictionary, cache):
    """Shortest word length reachable from here. 1 is a perfect clear."""
    if word in cache:
        return cache[word]
    cache[word] = len(word)  # guard; the graph only ever shrinks so it can't cycle
    best = len(word)
    for nxt in next_words(word, dictionary):
        best = min(best, depth(nxt, dictionary, cache) if len(nxt) > 1 else 1)
    cache[word] = best
    return best


def main():
    twl, popular = load(sys.argv[1]), load(sys.argv[2])
    dictionary = by_length(twl)
    cache = {}

    common = sorted(dictionary[5] & popular)
    seeds = [w for w in common if depth(w, dictionary, cache) <= 2]

    lines = [
        "// Generated by tools/build_words.py -- do not edit by hand.",
        "// Sources: " + "; ".join(SOURCES.values()),
        "",
        "// Every legal word, grouped by length and stored as one space-separated",
        "// string per length so the file stays small and parses fast.",
        "const RAW = {",
    ]
    for n in range(MIN_LEN, MAX_LEN + 1):
        lines.append(f'  {n}: "{" ".join(sorted(dictionary[n]))}",')
    lines += [
        "};",
        "",
        "// 5-letter openers with at least one path down to a 2-letter word. In",
        "// practice every one of these can also be cleared to a single letter.",
        'const SEED_WORDS = "' + " ".join(seeds) + '".split(" ");',
        "",
        "export const DICTIONARY = Object.fromEntries(",
        "  Object.entries(RAW).map(([n, words]) => [n, new Set(words.split(\" \"))])",
        ");",
        "export { SEED_WORDS };",
        "",
    ]
    with open("src/words.js", "w") as fh:
        fh.write("\n".join(lines))

    counts = {n: len(dictionary[n]) for n in dictionary}
    print(f"dictionary {counts} total {sum(counts.values())}")
    print(f"seeds {len(seeds)} of {len(common)} common 5-letter words")


if __name__ == "__main__":
    main()
