#!/usr/bin/env python3
"""Build the bundled dictionary and the list of solvable starting words.

Inputs are two public word lists (see SOURCES). Only the words are taken; the
NASPA list ships with definitions, which are Merriam-Webster's and are left
where they are. Definitions in the game come from Wiktionary at runtime.

The output, src/words.js, holds every legal 2-5 letter word plus a pre-verified
list of 5-letter openers that can be played all the way down.

Usage: python3 tools/build_words.py <lexicon.txt> <popular.txt>
"""
import sys
from string import ascii_lowercase

SOURCES = {
    "lexicon": "github.com/scrabblewords/scrabblewords (NWL2023, NASPA word list)",
    "popular": "github.com/dolph/dictionary (popular.txt)",
}
MIN_LEN, MAX_LEN = 2, 5


def load(path):
    """First token of each line, so a bare list and a defined one both work."""
    words = set()
    with open(path) as fh:
        for line in fh:
            token = line.split()[:1]
            if token and token[0].isalpha():
                words.add(token[0].lower())
    return words


def by_length(words):
    out = {n: set() for n in range(MIN_LEN, MAX_LEN + 1)}
    for w in words:
        if MIN_LEN <= len(w) <= MAX_LEN:
            out[len(w)].add(w)
    return out


def next_words(word, dictionary, used):
    """Every word reachable in one round.

    Keep len-2 consecutive letters and add one letter that has not been used
    yet, anywhere in the game so far.
    """
    n = len(word)
    if n == 2:
        return {c for c in "ai" if c in word}
    keep = n - 2
    found = set()
    for i in range(n - keep + 1):
        block = word[i:i + keep]
        for c in ascii_lowercase:
            if c in used:
                continue
            for candidate in (c + block, block + c):
                if candidate in dictionary[n - 1]:
                    found.add(candidate)
    return found


def solvable(word, dictionary, used):
    """Can this word be played all the way down to a single letter?"""
    if len(word) == 1:
        return True
    return any(
        solvable(nxt, dictionary, used | set(nxt))
        for nxt in next_words(word, dictionary, used)
    )


def main():
    lexicon, popular = load(sys.argv[1]), load(sys.argv[2])
    dictionary = by_length(lexicon)

    common = sorted(dictionary[5] & popular)
    seeds = [w for w in common if solvable(w, dictionary, set(w))]

    lines = [
        "// Generated by tools/build_words.py -- do not edit by hand.",
        "// Sources: " + "; ".join(SOURCES.values()),
        "",
        "// Every legal word, grouped by length and stored as one space-separated",
        "// string per length so the file stays small and parses fast.",
        "const RAW = {",
    ]
    for n in range(MIN_LEN, MAX_LEN + 1):
        lines.append(f'  {n}: "{" ".join(sorted(dictionary[n]))}",')
    lines += [
        "};",
        "",
        "// 5-letter openers that can be played all the way down to a single",
        "// letter without ever adding a letter that has already been used.",
        'const SEED_WORDS = "' + " ".join(seeds) + '".split(" ");',
        "",
        "export const DICTIONARY = Object.fromEntries(",
        "  Object.entries(RAW).map(([n, words]) => [n, new Set(words.split(\" \"))])",
        ");",
        "export { SEED_WORDS };",
        "",
    ]
    with open("src/words.js", "w") as fh:
        fh.write("\n".join(lines))

    counts = {n: len(dictionary[n]) for n in dictionary}
    print(f"dictionary {counts} total {sum(counts.values())}")
    print(f"seeds {len(seeds)} of {len(common)} common 5-letter words")


if __name__ == "__main__":
    main()
