#!/usr/bin/env python3
"""Build the bundled dictionary and the list of solvable starting words.

Inputs are two public word lists (see SOURCES). Only the words are taken; the
NASPA list ships with definitions, which are Merriam-Webster's and are left
where they are. Definitions in the game come from Wiktionary at runtime.

The output, src/words.js, holds every legal 2-5 letter word plus a pre-verified
list of 5-letter openers that can be played all the way down.

Usage: python3 tools/build_words.py <lexicon.txt> <popular.txt>
"""
import sys
from string import ascii_lowercase

SOURCES = {
    "lexicon": "github.com/scrabblewords/scrabblewords (NWL2023, NASPA word list)",
    "popular": "github.com/dolph/dictionary (popular.txt)",
}
MIN_LEN, MAX_LEN = 2, 5


def load(path):
    """First token of each line, so a bare list and a defined one both work."""
    words = set()
    with open(path) as fh:
        for line in fh:
            token = line.split()[:1]
            if token and token[0].isalpha():
                words.add(token[0].lower())
    return words


def by_length(words):
    out = {n: set() for n in range(MIN_LEN, MAX_LEN + 1)}
    for w in words:
        if MIN_LEN <= len(w) <= MAX_LEN:
            out[len(w)].add(w)
    return out


def next_words(word, dictionary, used):
    """Every word reachable in one round.

    Keep len-2 consecutive letters and add one letter that has not been used
    yet, anywhere in the game so far.
    """
    n = len(word)
    if n == 2:
        return {c for c in "ai" if c in word}
    keep = n - 2
    found = set()
    for i in range(n - keep + 1):
        block = word[i:i + keep]
        for c in ascii_lowercase:
            if c in used:
                continue
            for candidate in (c + block, block + c):
                if candidate in dictionary[n - 1]:
                    found.add(candidate)
    return found


# Banded from Scrabble tile values, matching src/game.js.
LETTER_VALUES = (
    {c: 1 for c in "aeilnorstu"}
    | {c: 2 for c in "dgbcmp"}
    | {c: 3 for c in "fhvwykjxqz"}
)
POINTS_PER_WORD = 2
FINISH_BONUS = 3
OBSCURITY_VETO = 3   # points of the ceiling that only unfamiliar words can reach


def options(word, dictionary, used, familiar=None):
    """Moves in a fixed order. The last letter drops on its own, so at two
    letters there is exactly one move, not a choice between A and I."""
    if len(word) == 2:
        return [c for c in word if c in "ai"][:1]
    found = sorted(next_words(word, dictionary, used))
    return [w for w in found if familiar is None or familiar(w)]


def gain(word, used):
    fresh = next((c for c in word if c not in used), None)
    return POINTS_PER_WORD + (LETTER_VALUES[fresh] if fresh else 0)


def ceiling(word, dictionary, used, familiar=None):
    """The most a run from here can score, the finish included."""
    if len(word) == 1:
        return FINISH_BONUS
    return max(
        (
            gain(nxt, used) + ceiling(nxt, dictionary, used | set(nxt), familiar)
            for nxt in options(word, dictionary, used, familiar)
        ),
        default=0,
    )


def greedy_score(word, dictionary, used):
    """What you get by always taking the most valuable letter on offer."""
    total = 0
    while len(word) > 1:
        moves = options(word, dictionary, used)
        if not moves:
            return total
        word = max(moves, key=lambda w: gain(w, used))
        total += gain(word, used)
        used = used | set(word)
    return total + FINISH_BONUS


def grade(word, dictionary, popular):
    """Easy when the obvious play is the best play; brutal when the best play
    needs words most people do not know."""
    used = set(word)
    top = ceiling(word, dictionary, used)
    familiar = lambda w: len(w) == 1 or w in popular
    if top - ceiling(word, dictionary, used, familiar) >= OBSCURITY_VETO:
        return "brutal"
    return "easy" if greedy_score(word, dictionary, used) == top else "hard"


def solvable(word, dictionary, used):
    """Can this word be played all the way down to a single letter?"""
    if len(word) == 1:
        return True
    return any(
        solvable(nxt, dictionary, used | set(nxt))
        for nxt in next_words(word, dictionary, used)
    )


def main():
    lexicon, popular = load(sys.argv[1]), load(sys.argv[2])
    dictionary = by_length(lexicon)

    common = sorted(dictionary[5] & popular)
    seeds = [w for w in common if solvable(w, dictionary, set(w))]

    tiers = {"easy": [], "hard": [], "brutal": []}
    for word in seeds:
        tiers[grade(word, dictionary, popular)].append(word)

    lines = [
        "// Generated by tools/build_words.py -- do not edit by hand.",
        "// Sources: " + "; ".join(SOURCES.values()),
        "",
        "// Every legal word, grouped by length and stored as one space-separated",
        "// string per length so the file stays small and parses fast.",
        "const RAW = {",
    ]
    for n in range(MIN_LEN, MAX_LEN + 1):
        lines.append(f'  {n}: "{" ".join(sorted(dictionary[n]))}",')
    lines += [
        "};",
        "",
        "// 5-letter openers that can be played all the way down to a single",
        "// letter without ever adding a letter that has already been used,",
        "// graded by whether the obvious play is also the best one. Deals whose",
        "// best runs need words most people do not know are set aside as brutal",
        "// however easy they are to play well.",
        "const SEEDS = {",
    ]
    for tier in ("easy", "hard", "brutal"):
        lines.append(f'  {tier}: "{" ".join(tiers[tier])}".split(" "),')
    lines += [
        "};",
        "",
        "const SEED_WORDS = [...SEEDS.easy, ...SEEDS.hard, ...SEEDS.brutal].sort();",
        "",
        "export const DICTIONARY = Object.fromEntries(",
        "  Object.entries(RAW).map(([n, words]) => [n, new Set(words.split(\" \"))])",
        ");",
        "export { SEED_WORDS, SEEDS };",
        "",
    ]
    with open("src/words.js", "w") as fh:
        fh.write("\n".join(lines))

    counts = {n: len(dictionary[n]) for n in dictionary}
    print(f"dictionary {counts} total {sum(counts.values())}")
    print(f"seeds {len(seeds)} of {len(common)} common 5-letter words")
    for tier in ("easy", "hard", "brutal"):
        share = len(tiers[tier]) / len(seeds) * 100
        print(f"  {tier:7} {len(tiers[tier]):5}  {share:4.1f}%")


if __name__ == "__main__":
    main()
